### ISSUE TITLE
extact failure

### ISSUE THREAD

**Issue by lifox1** [solliancenet/MCW-Migrating-to-Azure-SQL-Database-Managed-Instance#2]
TailspinToysReadOnlyContext.cs fails on extract of zip file but it has to do with path too long so ensure to tell users to download it in shorter path

**Comment by lifox1** [comment]
typo on slide 18 notes:
last bullet - should be not vs no

**Comment by lifox1** [comment]
Why recommending SQL DB hyperscale vs SQL DW?

**Comment by lifox1** [comment]
Training guide - states that Power BI will replace SSRS - this is not really possible.  Power BI only allows paginated reports now but does not replace all the functionality of SSRS so I think this may need to be more detailed here.  Unless something new came out that came out and I missed it?

**Comment by lifox1** [comment]
training guide - Game Databases  number one, addresses cost of IaaS vs PaaS and mentions that you can shut IaaS down but really - who shuts down a db server unless its non prod?  And with serverless tier now in Preview should that be mentioned??

**Comment by lifox1** [comment]
Overall thought after reading the training guide  - this is called a SQL MI workshop so it would gear participants to chose SQL MI.  So why not call it an Azure SQL workshop?  It is not really SQL MI specific based on what I read so far.

**Comment by lifox1** [comment]
In training guide it talks about DR at the end and suggests this which is the right suggestion but it is still in preview so there will be objections to doing this in MI
 auto-failover groups for the Azure SQL Database Managed Instances

**Comment by rodcolledge** [comment]
> Why recommending SQL DB hyperscale vs SQL DW?

I guess for maximum compatibility with their existing SQL 2008 data warehouse. If they move to SQL DW, some stuff would need to be re-architected. The reference to "scale-out" as a requirement could throw some people though as this is typically used to describe SQL DW architecture. It probably should say "READ scale out" as a requirement to make this clearer.

**Comment by kylebunting** [comment]
All comments addressed in commit b2161f0 , except for workshop rename. I propose renaming the workshop to "Migrating SQL database to Azure," and will send on to the MCW team.
