### ISSUE TITLE
feature parity with SQL2008r2 to SQLMI

### ISSUE THREAD

**Issue by lifox1** [solliancenet/MCW-Migrating-to-Azure-SQL-Database-Managed-Instance#3]
the instructions say their are no issues but getting one for powershell job step is not supported

**Comment by lzurcher** [comment]
> the instructions say their are no issues but getting one for powershell job step is not supported

Excercise 1, step 9

**Comment by kylebunting** [comment]
Lab updated with new screenshot and discussion of the feature parity with the powershell job.
