### ISSUE TITLE
data discovery and classification

### ISSUE THREAD

**Issue by lifox1** [solliancenet/MCW-Migrating-to-Azure-SQL-Database-Managed-Instance#5]
this was a little flaky.  It failed when I saved the first time and then it did not refresh so had to get out and get back into it for it to work.

**Comment by kylebunting** [comment]
Yes, it was the same for me. I have a note in the lab that this is in "preview," and how to handle it if you get an error when saving. Hopefully the usability of this feature will improve, as I think it is a great addition to the product. The other option would be to have the users go through SSMS to do the same thing, but that doesn't show off the capabilities in the Azure portal. I'll revisit this during the first test-fix or update of this workshop, and if it is still a problem consider moving it into SSMS.
