### ISSUE TITLE
enabling TDE

### ISSUE THREAD

**Issue by lifox1** [solliancenet/MCW-Migrating-to-Azure-SQL-Database-Managed-Instance#6]
It is in preview on the portal so can we now use the portal to do this in the instructions?

**Comment by kylebunting** [comment]
I'll look at this again. I tried using it through the portal, but when I clicked on the link for it, it just told me to enable in using SSMS, and there wasn't actually functionality in the portal to enable it.

**Comment by lifox1** [comment]
Yes - I did see that it just brings you to the documentation.  wondering if that is going to change but for now it is good.
