### ISSUE TITLE
HOL Step-by-step document Feedback

### ISSUE THREAD

**Issue by rodcolledge** [solliancenet/MCW-Migrating-to-Azure-SQL-Database-Managed-Instance#8]
Diagram on page 5 - "Read-on replica" should be "Read-only Replica". There's another reference to "Read-on" at the top of the next page.

Page 90 - Step 2 has the same image as step 1.

Page 96 - Step 4 - "cConfidential". I assume this should be "Confidential"?

Page 111 - the code after "paste the following parameter to end of the connection string" includes "sql", but should just be "ApplicationIntent=ReadOnly;"

**Comment by kylebunting** [comment]
Issues addressed is commit a093cd2.

For the comment about page 111, it is correct in the markdown, so that is most likely an issue with the process that converts the MD to HTML or a Word doc.
