### ISSUE TITLE
Feedback received via email

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [solliancenet/MCW-Migrating-to-Azure-SQL-Database-Managed-Instance#9]
From Craig Clayton:

I have undertaken the review of the trainer guide  / hands on lab walk thru. Here are my findings:

Exercise 1: Perform database assessments Task 3: Perform assessment for migration to Azure SQL Database Managed Instance
When assessing the SQL Server 2008 for MI , I came a cross this issue which isn’t in the  script

 ![image](https://user-images.githubusercontent.com/39317565/58347987-25322600-7e14-11e9-8448-cd524c289046.png)

Exercise 2: Migrate the database to SQL MI : Task 3: Create backup of TailspinToys database
When we are creating the SMB backup location , the lab shows just one location, however there will be another location left other from when we restored the back up to kick start the lab off. Should this be removed  or the screen shot updated to capture what the user will see?

![image](https://user-images.githubusercontent.com/39317565/58348041-51e63d80-7e14-11e9-981e-20f59eba60d1.png)

Exercise 2: Migrate the database to SQL MI : Task 4: Retrieve SQL MI and SQL Server 2008 VM connection information

When utilizing the cloud shell from the portal, it required much more than just create storage as it failed, it took me to go to advanced settings:
![image](https://user-images.githubusercontent.com/39317565/58348075-6f1b0c00-7e14-11e9-8caa-5c0b6855ab46.png)

Exercise 2: Migrate the database to SQL MI : Task 4: Task 5: Create a service principal

Point 1 shown below to be a little confusing and out of sequence with how I would approach it. I would drop this completely and move point 2 up and then  have the previous point 5 to tie it all together what you have been doing , rather than say at the outset as I feel it currently is a little misleading.
![image](https://user-images.githubusercontent.com/39317565/58348099-86f29000-7e14-11e9-9172-bd9a489bedab.png)

During this task I got this error due to my privileges:
![image](https://user-images.githubusercontent.com/39317565/58348127-9d98e700-7e14-11e9-98b9-47c1d8aa1116.png)

I have enjoyed the lab and it is very good. I could manually try and work round this issue with something like this Use portal to create an Azure Active Directory application and service principal that can access resources. However, I conscious that this would deviate from the lab and I’m not an AAD expert 😊.

**Comment by kylebunting** [comment]
1. Lab updated with new screenshot and discussion of the feature parity with the powershell job.
2. Step added to remove the previous backup destination.
3. Note added to tell user to enter advanced settings and configure the storage account there in the event of an error.
4. Steps cleaned up to remove confusion, as recommended.
5. Note added that appropriate permissions are needed in the Azure AD tenant to complete the creation of the service principal.
